# Generated by Django 2.1.5 on 2019-02-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='destinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, choices=[('Beaches', 0), ('Bike Rides', 1), ('Heritage', 2), ('Hot Air Ballooning', 3), ('Museums', 4), ('Resorts', 5), ('Road Trips', 6), ('Scenery', 7), ('Vacation Rentals', 8), ('Wildlife', 9)], max_length=255)),
                ('package_price', models.IntegerField(blank=True, default=0)),
                ('package_size', models.IntegerField(blank=True, default=0)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('pics', models.FileField(blank=True, max_length=255, upload_to='')),
                ('payment_info', models.CharField(blank=True, max_length=255)),
                ('reviews', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
