# Generated by Django 2.1.5 on 2019-02-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='username',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='p_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='destinations',
            field=models.ManyToManyField(to='dashboard.package'),
        ),
    ]
