# Generated by Django 2.1.5 on 2019-02-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, choices=[(0, 'Beaches'), (1, 'Bike Rides'), (2, 'Heritage'), (3, 'Hot Air Ballooning'), (4, 'Museums'), (5, 'Resorts'), (6, 'Road Trips'), (7, 'Scenery'), (8, 'Vacation Rentals'), (9, 'Wildlife')], max_length=255)),
                ('package_price', models.IntegerField(blank=True, default=0)),
                ('package_size', models.IntegerField(blank=True, default=0)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('pics', models.FileField(blank=True, max_length=255, upload_to='')),
                ('payment_info', models.CharField(blank=True, max_length=255)),
                ('reviews', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='destinations',
        ),
    ]
