# Generated by Django 2.1.5 on 2019-03-01 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190227_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='d_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='destinations',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.DeleteModel(
            name='booking',
        ),
    ]
