# Generated by Django 2.1.5 on 2019-03-01 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='destinations',
            new_name='packages',
        ),
    ]
