# Generated by Django 2.1.5 on 2019-02-11 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190210_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(blank=True, max_length=255)),
                ('p_guide', models.CharField(blank=True, max_length=255)),
                ('p_package_price', models.IntegerField(blank=True, default=0)),
                ('p_package_size', models.IntegerField(blank=True, default=0)),
                ('p_duration', models.CharField(blank=True, max_length=255)),
                ('p_description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='category',
            new_name='d_category',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='description',
            new_name='d_description',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='email',
            new_name='d_email',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='location',
            new_name='d_location',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='name',
            new_name='d_name',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='payment_info',
            new_name='d_payment_info',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='phone',
            new_name='d_phone',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='pics',
            new_name='d_pics',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='reviews',
            new_name='d_reviews',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='package_price',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='package_size',
        ),
        migrations.AddField(
            model_name='destination',
            name='d_days',
            field=models.DateField(blank=True, default='2019-01-01'),
        ),
        migrations.AddField(
            model_name='package',
            name='d_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.destination'),
        ),
    ]
