# Generated by Django 2.1.5 on 2019-03-02 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20190301_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='packages',
        ),
        migrations.AddField(
            model_name='booking',
            name='packages',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.package'),
            preserve_default=False,
        ),
    ]
