# Generated by Django 2.1.5 on 2019-02-13 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20190211_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ('d_name',)},
        ),
    ]
