# Generated by Django 2.1.5 on 2019-03-02 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20190302_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='d_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='packages',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.DeleteModel(
            name='booking',
        ),
    ]
