# Generated by Django 2.1.5 on 2019-02-13 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20190214_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='p_package_size',
        ),
    ]
