# Generated by Django 2.1.5 on 2019-02-14 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_package_p_package_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='p_package_price',
            new_name='p_price',
        ),
    ]
