# Generated by Django 2.1.5 on 2019-02-14 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20190214_0306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='p_guide',
            new_name='p_agent',
        ),
    ]
