# Generated by Django 2.1.5 on 2019-02-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20190214_0312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='d_category',
        ),
        migrations.AddField(
            model_name='package',
            name='p_category',
            field=models.CharField(blank=True, choices=[('Beaches', 'Beaches'), ('Bike Rides', 'Bike Rides'), ('Heritage', 'Heritage'), ('Hot Air Ballooning', 'Hot Air Ballooning'), ('Museums', 'Museums'), ('Resorts', 'Resorts'), ('Road Trips', 'Road Trips'), ('Scenery', 'Scenery'), ('Vacation Rentals', 'Vacation Rentals'), ('Wildlife', 'Wildlife')], max_length=255),
        ),
    ]
