# Generated by Django 2.1.5 on 2019-02-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20190214_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='d_reviews',
        ),
        migrations.AddField(
            model_name='package',
            name='p_reviews',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
