# Generated by Django 2.1.5 on 2019-03-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_booking_d_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='t_number',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
