# Generated by Django 2.1.5 on 2019-02-20 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20190214_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='p_agent',
            new_name='p_agency',
        ),
    ]
