# Generated by Django 2.1.5 on 2019-03-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20190302_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='agency_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
