# Generated by Django 2.1.7 on 2019-03-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_package_agency_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='d_payment_info',
        ),
        migrations.AddField(
            model_name='package',
            name='agency_phone',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='package',
            name='p_payment_info',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
