# Generated by Django 2.1.7 on 2019-03-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_remove_destination_d_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='d_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
