# Generated by Django 2.1.7 on 2019-03-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_remove_package_agency_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='packages',
        ),
        migrations.AddField(
            model_name='booking',
            name='packages',
            field=models.ManyToManyField(to='dashboard.package'),
        ),
    ]
