# Generated by Django 2.1.7 on 2019-03-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20190303_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='d_description',
            field=models.CharField(blank=True, max_length=999999),
        ),
    ]
