# Generated by Django 2.1.7 on 2019-03-04 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20190305_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='d_description',
        ),
    ]
