# Generated by Django 2.1.7 on 2019-03-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_remove_destination_d_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='d_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
