# Generated by Django 2.1.7 on 2019-03-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_destination_ddescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='ddescription',
        ),
        migrations.AlterField(
            model_name='destination',
            name='d_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
