# Generated by Django 2.1.7 on 2019-03-04 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_auto_20190305_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='packages',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='package',
            name='d_name',
        ),
        migrations.DeleteModel(
            name='booking',
        ),
        migrations.DeleteModel(
            name='destination',
        ),
        migrations.DeleteModel(
            name='package',
        ),
    ]
