# Generated by Django 2.1.7 on 2019-03-04 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0038_auto_20190305_0111'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(blank=True, max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('p_price', models.IntegerField(blank=True, default=0)),
                ('t_number', models.IntegerField(blank=True, default=1)),
            ],
        ),
        migrations.CreateModel(
            name='destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(blank=True, max_length=255)),
                ('d_location', models.CharField(blank=True, max_length=255)),
                ('d_description', models.CharField(blank=True, max_length=256)),
                ('d_pics', models.FileField(blank=True, max_length=255, upload_to='dashboard/')),
                ('d_days', models.DateField(blank=True, default='2019-01-01')),
                ('d_phone', models.CharField(blank=True, max_length=15)),
                ('d_email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ('d_name',),
            },
        ),
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(blank=True, max_length=255)),
                ('p_category', models.CharField(blank=True, choices=[('Beaches', 'Beaches'), ('Bike Rides', 'Bike Rides'), ('Heritage', 'Heritage'), ('Hot Air Ballooning', 'Hot Air Ballooning'), ('Museums', 'Museums'), ('Resorts', 'Resorts'), ('Road Trips', 'Road Trips'), ('Scenery', 'Scenery'), ('Vacation Rentals', 'Vacation Rentals'), ('Wildlife', 'Wildlife')], max_length=255)),
                ('p_agency', models.CharField(blank=True, max_length=255)),
                ('agency_phone', models.IntegerField(blank=True, default=1)),
                ('p_price', models.IntegerField(blank=True, default=0)),
                ('p_payment_info', models.CharField(blank=True, max_length=255)),
                ('p_duration', models.CharField(blank=True, max_length=255)),
                ('p_description', models.CharField(blank=True, max_length=255)),
                ('p_reviews', models.CharField(blank=True, max_length=255)),
                ('d_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.destination')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='packages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.package'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
