# Generated by Django 2.1.7 on 2019-03-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_auto_20190305_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='d_description',
            field=models.TextField(blank=True),
        ),
    ]
