# Generated by Django 2.1.7 on 2019-03-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_auto_20190305_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='p_description',
            field=models.TextField(blank=True),
        ),
    ]
