# Generated by Django 2.1.7 on 2019-03-06 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_auto_20190305_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='d_days',
        ),
        migrations.AddField(
            model_name='package',
            name='from_day',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='package',
            name='to_day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 5, 20, 22, 21, 863645)),
        ),
    ]
