# Generated by Django 2.1.7 on 2019-03-06 17:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_auto_20190306_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='to_day',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 4, 5, 17, 25, 16, 112689, tzinfo=utc)),
        ),
    ]
