# Generated by Django 2.1.7 on 2019-03-06 18:06

import dashboard.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_auto_20190306_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='from_day',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='to_day',
            field=models.DateField(blank=True, default=dashboard.models.one_month_from_today, null=True),
        ),
    ]
