# Generated by Django 2.1.7 on 2019-03-06 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_auto_20190306_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='dashboard/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ('p_name', 'd_name')},
        ),
        migrations.RemoveField(
            model_name='destination',
            name='d_pics',
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dashboard.destination'),
        ),
    ]
