# Generated by Django 2.1.7 on 2019-03-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_auto_20190306_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='d_pics',
            field=models.FileField(blank=True, max_length=255, upload_to='dashboard/'),
        ),
    ]
