# Generated by Django 2.1.7 on 2019-03-06 19:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_destination_d_pics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='d_pics',
        ),
        migrations.AddField(
            model_name='destination',
            name='d_pic1',
            field=models.FileField(blank=True, upload_to='dashboard/'),
        ),
        migrations.AddField(
            model_name='destination',
            name='d_pic2',
            field=models.FileField(blank=True, upload_to='dashboard/'),
        ),
        migrations.AddField(
            model_name='destination',
            name='d_pic3',
            field=models.FileField(blank=True, upload_to='dashboard/'),
        ),
        migrations.AddField(
            model_name='destination',
            name='d_uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
