# Generated by Django 2.1.7 on 2019-03-06 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_auto_20190306_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pd_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.destination'),
            preserve_default=False,
        ),
    ]
