# Generated by Django 2.1.7 on 2019-03-06 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_booking_pd_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='pd_name',
        ),
        migrations.AlterField(
            model_name='booking',
            name='d_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.destination'),
        ),
    ]
