# Generated by Django 2.1.7 on 2019-03-06 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_auto_20190306_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='d_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='packages',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.DeleteModel(
            name='booking',
        ),
    ]
