# Generated by Django 2.1.7 on 2019-03-13 09:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_package_favorite_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(blank=True, max_length=255)),
                ('pricep_adult', models.IntegerField(blank=True, default=0)),
                ('pricep_kid', models.IntegerField(blank=True, default=0)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.destination')),
            ],
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('-date_added',)},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='t_number',
            new_name='adults',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='p_price',
            new_name='kids',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='p_price',
            new_name='p_slots',
        ),
        migrations.RemoveField(
            model_name='package',
            name='favorite_colors',
        ),
        migrations.RemoveField(
            model_name='package',
            name='p_duration',
        ),
        migrations.AddField(
            model_name='booking',
            name='days',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pricep_adult',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='pricep_day',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='pricep_kid',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='pricep_adult',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='pricep_day',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='pricep_kid',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='package',
            name='agency_phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='hotel',
            field=models.OneToOneField(default=36, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Hotel'),
        ),
    ]
