# Generated by Django 2.1.7 on 2019-03-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_package_favorite_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hotel',
            field=models.CharField(blank=True, choices=[('blue', 'Blue'), ('green', 'Green'), ('black', 'Black')], max_length=255),
        ),
    ]
