# Generated by Django 2.1.7 on 2019-03-07 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_booking_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(blank=True, max_length=255)),
                ('pricep_adult', models.IntegerField(blank=True, default=0)),
                ('pricep_kid', models.IntegerField(blank=True, default=0)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.destination')),
            ],
        ),
        migrations.RenameField(
            model_name='package',
            old_name='p_price',
            new_name='pricep_adult',
        ),
        migrations.AddField(
            model_name='package',
            name='pricep_day',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='pricep_kid',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
