# Generated by Django 2.1.7 on 2019-03-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_auto_20190307_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='hotel',
        ),
        migrations.AddField(
            model_name='booking',
            name='adults',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='kids',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
