# Generated by Django 2.1.7 on 2019-03-08 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_auto_20190308_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='t_number',
            new_name='days',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='p_price',
            new_name='pricep_adult',
        ),
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pricep_day',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='pricep_kid',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
