# Generated by Django 2.1.7 on 2019-03-13 09:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0056_auto_20190313_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('adults', models.IntegerField(blank=True, default=1)),
                ('kids', models.IntegerField(blank=True, default=0)),
                ('pricep_adult', models.IntegerField(blank=True, default=0)),
                ('pricep_kid', models.IntegerField(blank=True, default=0)),
                ('days', models.IntegerField(blank=True, default=1)),
                ('start_date', models.DateTimeField(blank=True, default=datetime.date.today, null=True)),
                ('end_date', models.DateTimeField(blank=True, default=datetime.date.today, null=True)),
                ('pricep_day', models.IntegerField(blank=True, default=0)),
                ('d_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.destination')),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(blank=True, max_length=255)),
                ('pricep_adult', models.IntegerField(blank=True, default=0)),
                ('pricep_kid', models.IntegerField(blank=True, default=0)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.destination')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='hotel',
            field=models.OneToOneField(default=36, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Hotel'),
        ),
        migrations.AddField(
            model_name='booking',
            name='packages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.package'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
