# Generated by Django 2.1.7 on 2019-03-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_auto_20190308_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
