# Generated by Django 2.1.7 on 2019-03-14 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0057_auto_20190313_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='d_name',
        ),
        migrations.AlterField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Hotel'),
        ),
    ]
