# Generated by Django 2.1.7 on 2019-03-08 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0057_booking_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_price',
        ),
    ]
