# Generated by Django 2.1.7 on 2019-03-17 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0060_booking_agency'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(blank=True, max_length=255)),
                ('hotel', models.CharField(blank=True, max_length=255)),
                ('date_added', models.DateTimeField(blank=True)),
                ('adults', models.IntegerField(blank=True, default=1)),
                ('kids', models.IntegerField(blank=True, default=0)),
                ('pricep_adult', models.IntegerField(blank=True, default=0)),
                ('pricep_kid', models.IntegerField(blank=True, default=0)),
                ('days', models.IntegerField(blank=True, default=1)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('pricep_day', models.IntegerField(blank=True, default=0)),
                ('transaction_status', models.CharField(blank=True, max_length=255)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
