# Generated by Django 2.1.7 on 2019-03-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0061_auto_20190311_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='p_duration',
        ),
        migrations.AlterField(
            model_name='package',
            name='agency_phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
