# Generated by Django 2.1.7 on 2019-03-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0062_auto_20190318_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
