# Generated by Django 2.1.7 on 2019-03-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0063_booking_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='hotel',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
