# Generated by Django 2.1.7 on 2019-03-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0063_auto_20190318_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='packages',
            new_name='p_name2',
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_added',
            field=models.DateTimeField(blank=True),
        ),
    ]
