# Generated by Django 2.1.7 on 2019-03-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0064_auto_20190312_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='hotel',
        ),
        migrations.AddField(
            model_name='booking',
            name='hotel',
            field=models.ManyToManyField(to='dashboard.Hotel'),
        ),
    ]
