# Generated by Django 2.1.7 on 2019-03-12 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0065_auto_20190312_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='hotel',
        ),
        migrations.AddField(
            model_name='booking',
            name='hotel',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Hotel'),
            preserve_default=False,
        ),
    ]
