# Generated by Django 2.1.7 on 2019-03-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0066_auto_20190312_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='hotel',
        ),
        migrations.AddField(
            model_name='booking',
            name='hotel',
            field=models.ManyToManyField(to='dashboard.Hotel'),
        ),
    ]
