# Generated by Django 2.1.7 on 2019-03-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0066_auto_20190318_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='d_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
