# Generated by Django 2.1.7 on 2019-03-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0067_booking_d_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
