# Generated by Django 2.1.7 on 2019-03-12 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0067_auto_20190312_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='hotel',
        ),
    ]
