# Generated by Django 2.1.7 on 2019-03-19 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_package_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='availability',
            new_name='availabile',
        ),
    ]
