# Generated by Django 2.1.7 on 2019-03-12 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_remove_booking_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='d_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='packages',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.DeleteModel(
            name='booking',
        ),
    ]
