# Generated by Django 2.1.7 on 2019-03-20 11:36

import dashboard.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0070_auto_20190319_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, validators=[dashboard.models.validate_date]),
        ),
    ]
