# Generated by Django 2.1.7 on 2019-03-12 14:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0071_auto_20190312_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('adults', models.IntegerField(blank=True, default=1)),
                ('kids', models.IntegerField(blank=True, default=0)),
                ('pricep_adult', models.IntegerField(blank=True, default=0)),
                ('pricep_kid', models.IntegerField(blank=True, default=0)),
                ('days', models.IntegerField(blank=True, default=1)),
                ('start_date', models.DateTimeField(blank=True, default=datetime.date.today, null=True)),
                ('end_date', models.DateTimeField(blank=True, default=datetime.date.today, null=True)),
                ('pricep_day', models.IntegerField(blank=True, default=0)),
                ('d_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.destination')),
                ('packages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
    ]
