# Generated by Django 2.1.7 on 2019-03-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0072_auto_20190321_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amountpaid',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pricep_adult',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pricep_day',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pricep_kid',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='pricep_adult',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='pricep_kid',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='package',
            name='pricep_adult',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='package',
            name='pricep_day',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='package',
            name='pricep_kid',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pricep_day',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pricep_kid',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
