# Generated by Django 2.1.7 on 2019-03-12 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0073_booking_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='p_hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Hotel'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='booking',
            name='hotel',
        ),
        migrations.AddField(
            model_name='booking',
            name='hotel',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
