# Generated by Django 2.1.7 on 2019-03-21 17:53

import dashboard.models
import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0073_auto_20190321_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationimage',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pricep_day',
        ),
        migrations.RemoveField(
            model_name='package',
            name='p_payment_info',
        ),
        migrations.RemoveField(
            model_name='package',
            name='p_reviews',
        ),
        migrations.RemoveField(
            model_name='package',
            name='pricep_day',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='pricep_day',
        ),
        migrations.AddField(
            model_name='destination',
            name='d_reviews',
            field=models.CharField(blank=True, max_length=255, verbose_name='Reviews'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='adults',
            field=models.IntegerField(blank=True, default=1, verbose_name='Adults'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='agency',
            field=models.CharField(blank=True, max_length=255, verbose_name='Travel Agency'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='d_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='days',
            field=models.IntegerField(blank=True, default=1, verbose_name='Days'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True, verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='kids',
            field=models.IntegerField(blank=True, default=0, verbose_name='Kids'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pricep_adult',
            field=models.FloatField(blank=True, default=0, verbose_name='Price per Adult'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pricep_kid',
            field=models.FloatField(blank=True, default=0, verbose_name='Price per Kid'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, validators=[dashboard.models.validate_date], verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='d_description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='d_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='d_location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='d_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='d_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='d_pic1',
            field=models.FileField(blank=True, upload_to='dashboard/', verbose_name='Pic 1'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='d_pic2',
            field=models.FileField(blank=True, upload_to='dashboard/', verbose_name='Pic 1'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='d_pic3',
            field=models.FileField(blank=True, upload_to='dashboard/', verbose_name='Pic 3'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='d_uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='h_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Hotel'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='pricep_adult',
            field=models.FloatField(blank=True, default=0, verbose_name='Price per Adult'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='pricep_kid',
            field=models.FloatField(blank=True, default=0, verbose_name='Price per Kid'),
        ),
        migrations.AlterField(
            model_name='package',
            name='agency_phone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='package',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Available?'),
        ),
        migrations.AlterField(
            model_name='package',
            name='from_day',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='package',
            name='p_agency',
            field=models.CharField(blank=True, max_length=255, verbose_name='Agency'),
        ),
        migrations.AlterField(
            model_name='package',
            name='p_category',
            field=models.CharField(blank=True, choices=[('Beaches', 'Beaches'), ('Bike Rides', 'Bike Rides'), ('Heritage', 'Heritage'), ('Hot Air Ballooning', 'Hot Air Ballooning'), ('Museums', 'Museums'), ('Resorts', 'Resorts'), ('Road Trips', 'Road Trips'), ('Scenery', 'Scenery'), ('Vacation Rentals', 'Vacation Rentals'), ('Wildlife', 'Wildlife')], max_length=255, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='package',
            name='p_description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='package',
            name='p_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Package Name'),
        ),
        migrations.AlterField(
            model_name='package',
            name='p_slots',
            field=models.IntegerField(blank=True, default=0, verbose_name='Number Slots'),
        ),
        migrations.AlterField(
            model_name='package',
            name='pricep_adult',
            field=models.FloatField(blank=True, default=0, verbose_name='Price per Adult'),
        ),
        migrations.AlterField(
            model_name='package',
            name='pricep_kid',
            field=models.FloatField(blank=True, default=0, verbose_name='Price per Kid'),
        ),
        migrations.AlterField(
            model_name='package',
            name='to_day',
            field=models.DateField(blank=True, default=dashboard.models.one_month_from_today, null=True, verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='adults',
            field=models.IntegerField(blank=True, default=1, verbose_name='Adults'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='agency',
            field=models.CharField(blank=True, max_length=255, verbose_name='Travel Agency'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amountpaid',
            field=models.FloatField(blank=True, default=0, verbose_name='Amount Paid'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_added',
            field=models.DateTimeField(blank=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_paid',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Paid'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='days',
            field=models.IntegerField(blank=True, default=1, verbose_name='Days'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='hotel',
            field=models.CharField(blank=True, max_length=255, verbose_name='Preferred Hotel'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='kids',
            field=models.IntegerField(blank=True, default=0, verbose_name='Kids'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pricep_adult',
            field=models.FloatField(blank=True, default=0, verbose_name='Price per Adult'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pricep_kid',
            field=models.FloatField(blank=True, default=0, verbose_name='Price per Kid'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Transaction ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_status',
            field=models.CharField(blank=True, max_length=255, verbose_name='Transaction Status'),
        ),
        migrations.DeleteModel(
            name='DestinationImage',
        ),
    ]
