# Generated by Django 2.1.7 on 2019-03-23 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0074_auto_20190321_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='agencyname',
            field=models.CharField(blank=True, max_length=255, verbose_name='Travel Agency'),
        ),
        migrations.AddField(
            model_name='payment',
            name='agencyname',
            field=models.CharField(blank=True, max_length=255, verbose_name='Travel Agency'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='agency',
            field=models.CharField(blank=True, max_length=255, verbose_name='Agency'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Hotel', verbose_name='Hotel'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='p_name2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.package', verbose_name='Package'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='d_uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.destination', verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='package',
            name='agency',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Agency'),
        ),
        migrations.AlterField(
            model_name='package',
            name='d_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.destination', verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='package',
            name='p_agency',
            field=models.CharField(blank=True, max_length=255, verbose_name='Travel Agency'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='agency',
            field=models.CharField(blank=True, max_length=255, verbose_name='Agency'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amountpaid',
            field=models.FloatField(blank=True, default=0, verbose_name='Amount Paid ($USD)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.booking', verbose_name='Package'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
    ]
