# Generated by Django 2.1.7 on 2019-03-23 11:01

import dashboard.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0076_auto_20190323_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, validators=[dashboard.models.validate_date], verbose_name='From'),
        ),
    ]
