# Generated by Django 2.1.7 on 2019-03-23 11:03

import dashboard.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0077_auto_20190323_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, validators=[dashboard.models.validate_date], verbose_name='From'),
        ),
    ]
