# Generated by Django 2.1.7 on 2019-03-23 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0078_auto_20190323_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='To'),
        ),
    ]
