# Generated by Django 2.1.7 on 2019-03-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0079_auto_20190323_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='To'),
        ),
    ]
