# Generated by Django 2.1.7 on 2019-03-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0080_auto_20190323_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user_full',
            field=models.CharField(blank=True, max_length=255, verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user_full',
            field=models.CharField(blank=True, max_length=255, verbose_name='Client'),
        ),
    ]
