# Generated by Django 2.1.7 on 2019-03-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0081_auto_20190323_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='clientemail',
            field=models.CharField(blank=True, max_length=255, verbose_name="Client's Email"),
        ),
        migrations.AddField(
            model_name='payment',
            name='clientemail',
            field=models.CharField(blank=True, max_length=255, verbose_name="Client's Email"),
        ),
    ]
