# Generated by Django 2.1.7 on 2019-03-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0082_auto_20190323_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved?'),
        ),
    ]
