# Generated by Django 2.1.7 on 2019-03-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0083_booking_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='agencycontact',
            field=models.CharField(blank=True, max_length=255, verbose_name='Agency Contact'),
        ),
        migrations.AddField(
            model_name='payment',
            name='agencycontact',
            field=models.CharField(blank=True, max_length=255, verbose_name='Agency Contact'),
        ),
    ]
