# Generated by Django 2.1.7 on 2019-03-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0084_auto_20190323_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Approved?'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Booked'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='d_pic2',
            field=models.FileField(blank=True, upload_to='dashboard/', verbose_name='Pic 2'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='clientemail',
            field=models.CharField(blank=True, max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_added',
            field=models.DateTimeField(blank=True, verbose_name='Date Booked'),
        ),
    ]
