# Generated by Django 2.1.7 on 2019-03-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0085_auto_20190324_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Paid?'),
        ),
    ]
