# Generated by Django 2.1.7 on 2019-03-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0087_package_agencyemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='agencyemail',
            field=models.CharField(blank=True, max_length=255, verbose_name='Agency Email'),
        ),
    ]
